package com.lowbottgames.agecalculator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.lowbottgames.agecalculator.PersonModel;

import com.lowbottgames.agecalculator.PersonModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personModelDaoConfig;

    private final PersonModelDao personModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personModelDaoConfig = daoConfigMap.get(PersonModelDao.class).clone();
        personModelDaoConfig.initIdentityScope(type);

        personModelDao = new PersonModelDao(personModelDaoConfig, this);

        registerDao(PersonModel.class, personModelDao);
    }
    
    public void clear() {
        personModelDaoConfig.getIdentityScope().clear();
    }

    public PersonModelDao getPersonModelDao() {
        return personModelDao;
    }

}
