package com.lowbottgames.agecalculator;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.lowbottgames.agecalculator.PersonModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PERSON_MODEL.
*/
public class PersonModelDao extends AbstractDao<PersonModel, Long> {

    public static final String TABLENAME = "PERSON_MODEL";

    /**
     * Properties of entity PersonModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Day = new Property(2, Integer.class, "day", false, "DAY");
        public final static Property Month = new Property(3, Integer.class, "month", false, "MONTH");
        public final static Property Year = new Property(4, Integer.class, "year", false, "YEAR");
        public final static Property Hour = new Property(5, Integer.class, "hour", false, "HOUR");
        public final static Property Minute = new Property(6, Integer.class, "minute", false, "MINUTE");
    };


    public PersonModelDao(DaoConfig config) {
        super(config);
    }
    
    public PersonModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PERSON_MODEL' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'DAY' INTEGER," + // 2: day
                "'MONTH' INTEGER," + // 3: month
                "'YEAR' INTEGER," + // 4: year
                "'HOUR' INTEGER," + // 5: hour
                "'MINUTE' INTEGER);"); // 6: minute
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PERSON_MODEL'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PersonModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        Integer day = entity.getDay();
        if (day != null) {
            stmt.bindLong(3, day);
        }
 
        Integer month = entity.getMonth();
        if (month != null) {
            stmt.bindLong(4, month);
        }
 
        Integer year = entity.getYear();
        if (year != null) {
            stmt.bindLong(5, year);
        }
 
        Integer hour = entity.getHour();
        if (hour != null) {
            stmt.bindLong(6, hour);
        }
 
        Integer minute = entity.getMinute();
        if (minute != null) {
            stmt.bindLong(7, minute);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PersonModel readEntity(Cursor cursor, int offset) {
        PersonModel entity = new PersonModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // day
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // month
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // year
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // hour
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6) // minute
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PersonModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDay(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setMonth(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setYear(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setHour(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setMinute(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PersonModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PersonModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
